/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Customer;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Справочник контрагентов
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>purchase.customer.customer_code</code>. Код контрагента
     */
    public void setCustomerCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_code</code>. Код контрагента
     */
    public String getCustomerCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>purchase.customer.customer_name</code>. Наименование
     */
    public void setCustomerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_name</code>. Наименование
     */
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>purchase.customer.customer_inn</code>. ИНН
     */
    public void setCustomerInn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_inn</code>. ИНН
     */
    public String getCustomerInn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>purchase.customer.customer_kpp</code>. КПП
     */
    public void setCustomerKpp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_kpp</code>. КПП
     */
    public String getCustomerKpp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>purchase.customer.customer_legal_address</code>. Юр.
     * адрес
     */
    public void setCustomerLegalAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_legal_address</code>. Юр.
     * адрес
     */
    public String getCustomerLegalAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>purchase.customer.customer_postal_address</code>.
     * Почтовый адрес
     */
    public void setCustomerPostalAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_postal_address</code>.
     * Почтовый адрес
     */
    public String getCustomerPostalAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>purchase.customer.customer_email</code>. Электронная
     * почта
     */
    public void setCustomerEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_email</code>. Электронная
     * почта
     */
    public String getCustomerEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>purchase.customer.customer_code_main</code>. Вышестоящий
     * контрагент
     */
    public void setCustomerCodeMain(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>purchase.customer.customer_code_main</code>. Вышестоящий
     * контрагент
     */
    public String getCustomerCodeMain() {
        return (String) get(7);
    }

    /**
     * Setter for <code>purchase.customer.is_organization</code>. Юр. лицо
     */
    public void setIsOrganization(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>purchase.customer.is_organization</code>. Юр. лицо
     */
    public Boolean getIsOrganization() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>purchase.customer.is_person</code>. Физ. лицо
     */
    public void setIsPerson(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>purchase.customer.is_person</code>. Физ. лицо
     */
    public Boolean getIsPerson() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(String customerCode, String customerName, String customerInn, String customerKpp, String customerLegalAddress, String customerPostalAddress, String customerEmail, String customerCodeMain, Boolean isOrganization, Boolean isPerson) {
        super(Customer.CUSTOMER);

        setCustomerCode(customerCode);
        setCustomerName(customerName);
        setCustomerInn(customerInn);
        setCustomerKpp(customerKpp);
        setCustomerLegalAddress(customerLegalAddress);
        setCustomerPostalAddress(customerPostalAddress);
        setCustomerEmail(customerEmail);
        setCustomerCodeMain(customerCodeMain);
        setIsOrganization(isOrganization);
        setIsPerson(isPerson);
        resetChangedOnNotNull();
    }
}
