/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Customer;
import com.example.jooq.tables.Lot;
import com.example.jooq.tables.records.CustomerRecord;
import com.example.jooq.tables.records.LotRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_PK = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pk"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerRecord, CustomerRecord> CUSTOMER__CUSTOMER_CUSTOMER_FK = Internal.createForeignKey(Customer.CUSTOMER, DSL.name("customer_customer_fk"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE_MAIN }, Keys.CUSTOMER_PK, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final ForeignKey<LotRecord, CustomerRecord> LOT__LOT_CUSTOMER_FK = Internal.createForeignKey(Lot.LOT, DSL.name("lot_customer_fk"), new TableField[] { Lot.LOT.CUSTOMER_CODE }, Keys.CUSTOMER_PK, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
}
