/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Customer;
import com.example.jooq.tables.Lot;


/**
 * Convenience access to all tables in purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Справочник контрагентов
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * Лоты
     */
    public static final Lot LOT = Lot.LOT;
}
