/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Purchase;
import com.example.jooq.tables.Customer.CustomerPath;
import com.example.jooq.tables.records.LotRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Лоты
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lot extends TableImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>purchase.lot</code>
     */
    public static final Lot LOT = new Lot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LotRecord> getRecordType() {
        return LotRecord.class;
    }

    /**
     * The column <code>purchase.lot.lot_name</code>. Наименование лота
     */
    public final TableField<LotRecord, String> LOT_NAME = createField(DSL.name("lot_name"), SQLDataType.VARCHAR, this, "Наименование лота");

    /**
     * The column <code>purchase.lot.customer_code</code>. Код контрагента
     */
    public final TableField<LotRecord, String> CUSTOMER_CODE = createField(DSL.name("customer_code"), SQLDataType.VARCHAR, this, "Код контрагента");

    /**
     * The column <code>purchase.lot.price</code>. Начальная стоимость
     */
    public final TableField<LotRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC, this, "Начальная стоимость");

    /**
     * The column <code>purchase.lot.currency_code</code>. Валюта
     */
    public final TableField<LotRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR, this, "Валюта");

    /**
     * The column <code>purchase.lot.nds_rate</code>. Код НДС
     */
    public final TableField<LotRecord, String> NDS_RATE = createField(DSL.name("nds_rate"), SQLDataType.VARCHAR, this, "Код НДС");

    /**
     * The column <code>purchase.lot.place_delivery</code>. Грузополучатель
     */
    public final TableField<LotRecord, String> PLACE_DELIVERY = createField(DSL.name("place_delivery"), SQLDataType.VARCHAR, this, "Грузополучатель");

    /**
     * The column <code>purchase.lot.date_delivery</code>. Дата доставки
     */
    public final TableField<LotRecord, LocalDateTime> DATE_DELIVERY = createField(DSL.name("date_delivery"), SQLDataType.LOCALDATETIME(6), this, "Дата доставки");

    private Lot(Name alias, Table<LotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lot(Name alias, Table<LotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Лоты"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(String alias) {
        this(DSL.name(alias), LOT);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(Name alias) {
        this(alias, LOT);
    }

    /**
     * Create a <code>purchase.lot</code> table reference
     */
    public Lot() {
        this(DSL.name("lot"), null);
    }

    public <O extends Record> Lot(Table<O> path, ForeignKey<O, LotRecord> childPath, InverseForeignKey<O, LotRecord> parentPath) {
        super(path, childPath, parentPath, LOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LotPath extends Lot implements Path<LotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LotPath(Table<O> path, ForeignKey<O, LotRecord> childPath, InverseForeignKey<O, LotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LotPath(Name alias, Table<LotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LotPath as(String alias) {
            return new LotPath(DSL.name(alias), this);
        }

        @Override
        public LotPath as(Name alias) {
            return new LotPath(alias, this);
        }

        @Override
        public LotPath as(Table<?> alias) {
            return new LotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Purchase.PURCHASE;
    }

    @Override
    public List<ForeignKey<LotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOT__LOT_CUSTOMER_FK);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>purchase.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.LOT__LOT_CUSTOMER_FK, null);

        return _customer;
    }

    @Override
    public List<Check<LotRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("currency_code_check"), "(((currency_code)::text = ANY ((ARRAY['RUB'::character varying, 'USD'::character varying, 'EUR'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("nds_rate_check"), "(((nds_rate)::text = ANY ((ARRAY['Без НДС'::character varying, '18%'::character varying, '20%'::character varying])::text[])))", true)
        );
    }

    @Override
    public Lot as(String alias) {
        return new Lot(DSL.name(alias), this);
    }

    @Override
    public Lot as(Name alias) {
        return new Lot(alias, this);
    }

    @Override
    public Lot as(Table<?> alias) {
        return new Lot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(String name) {
        return new Lot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Name name) {
        return new Lot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Table<?> name) {
        return new Lot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition condition) {
        return new Lot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
